name: k6 Cloud Load Test

on:
  push:
    branches:
      - '**'

jobs:
  run-cloud-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 test in Grafana Cloud
        uses: grafana/run-k6-action@v1
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
        with:
          path: test.js
          cloud-run-locally: true      # ✅ Відправка результатів у Grafana Cloud
          cloud-comment-on-pr: false   # за бажанням, коментар на PR


